### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tcharl** [OsgiliathEnterprise/platform#55]
- [x] Minikube #57 

- [x] LetsEncrypt #59 

- [x] Kerberos incl . LetsEncrypt #54 

- [x] Bind9 incl. GSSAPI Kerb. #62 

- [x] NFS incl. Kerb + DNS #64 

- [x] LDAP incl  Kerb + NFS + LetsEncrypt + LDAP
